### ISSUE TITLE
本地启动启动PolarDB-X CN失败

### ISSUE THREAD

**Issue by lreeze123** [polardb/polardbx-sql#214]
按照操作手册的方式，拉的是main分支，启动PolarDB-X DN正常，启动PolarDB-X CN时，报错如下：

2024-08-19 10:07:04.059 INFO  [TDDL] XProtocol NIOWorker start with 32 threads and 16777216 bytes buf per thread., tddl version: 5.4.19-20240819
2024-08-19 10:07:04.788 INFO  [TDDL] XConnectionManager new datasource to my_polarx@127.0.0.1:32886 id is 0 NOW_GLOBAL_SESSION: 0, tddl version: 5.4.19-20240819
2024-08-19 10:07:04.794 INFO  [TDDL] New session: XSession sid=2 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:04.798 INFO  [TDDL] X-NIO-Client /127.0.0.1:57082 to /127.0.0.1:32886 connect success, connect time: 2261us., tddl version: 5.4.19-20240819
2024-08-19 10:07:04.818 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:57082 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:57082 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:04.818 INFO  [TDDL] X-NIO-Client /127.0.0.1:57082 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.350 INFO  [TDDL] New session: XSession sid=3 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] New session: XSession sid=4 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] X-NIO-Client /127.0.0.1:53630 to /127.0.0.1:32886 connect success, connect time: 234us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] New session: XSession sid=5 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] New session: XSession sid=6 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] X-NIO-Client /127.0.0.1:53646 to /127.0.0.1:32886 connect success, connect time: 247us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] X-NIO-Client /127.0.0.1:53652 to /127.0.0.1:32886 connect success, connect time: 180us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] New session: XSession sid=7 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] New session: XSession sid=8 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.351 INFO  [TDDL] X-NIO-Client /127.0.0.1:53674 to /127.0.0.1:32886 connect success, connect time: 127us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] New session: XSession sid=9 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53664 to /127.0.0.1:32886 connect success, connect time: 230us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] New session: XSession sid=10 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53682 to /127.0.0.1:32886 connect success, connect time: 114us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53694 to /127.0.0.1:32886 connect success, connect time: 131us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53710 to /127.0.0.1:32886 connect success, connect time: 92us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] New session: XSession sid=11 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 WARN  [TDDL] Found bad XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886 and remove it., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53646 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53646 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53646 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53726 to /127.0.0.1:32886 connect success, connect time: 213us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53630 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53630 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.352 INFO  [TDDL] New session: XSession sid=12 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53630 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] New session: XSession sid=13 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.352 INFO  [TDDL] X-NIO-Client /127.0.0.1:53730 to /127.0.0.1:32886 connect success, connect time: 112us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=14 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53736 to /127.0.0.1:32886 connect success, connect time: 106us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=15 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53738 to /127.0.0.1:32886 connect success, connect time: 112us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53710 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53710 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=16 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53710 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53746 to /127.0.0.1:32886 connect success, connect time: 102us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53652 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53652 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53652 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=17 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53664 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53664 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53754 to /127.0.0.1:32886 connect success, connect time: 95us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53748 to /127.0.0.1:32886 connect success, connect time: 232us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=18 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53726 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53726 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53664 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53674 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53674 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53726 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 INFO  [TDDL] New session: XSession sid=19 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.353 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53694 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53694 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53730 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53730 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.353 INFO  [TDDL] X-NIO-Client /127.0.0.1:53770 to /127.0.0.1:32886 connect success, connect time: 136us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53674 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53736 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53736 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53682 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53682 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53736 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] New session: XSession sid=20 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53694 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53784 to /127.0.0.1:32886 connect success, connect time: 112us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53730 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53682 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] New session: XSession sid=21 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53790 to /127.0.0.1:32886 connect success, connect time: 110us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53746 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53746 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 INFO  [TDDL] New session: XSession sid=22 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53738 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53738 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53746 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53754 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53754 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53798 to /127.0.0.1:32886 connect success, connect time: 99us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53738 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] New session: XSession sid=23 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53754 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.354 INFO  [TDDL] X-NIO-Client /127.0.0.1:53800 to /127.0.0.1:32886 connect success, connect time: 104us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53816 to /127.0.0.1:32886 connect success, connect time: 133us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53784 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53784 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.355 INFO  [TDDL] New session: XSession sid=24 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53748 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53748 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53770 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53770 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53784 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53748 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] New session: XSession sid=25 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53770 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53790 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53790 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53820 to /127.0.0.1:32886 connect success, connect time: 107us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] New session: XSession sid=26 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53790 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53826 to /127.0.0.1:32886 connect success, connect time: 112us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] New session: XSession sid=27 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53842 to /127.0.0.1:32886 connect success, connect time: 98us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53800 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53800 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-08-19 10:07:14.355 INFO  [TDDL] New session: XSession sid=28 status=Init from XClient of X-NIO-Client to my_polarx#44a880a5@127.0.0.1:32886, tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53800 to /127.0.0.1:32886 close socket., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53844 to /127.0.0.1:32886 connect success, connect time: 117us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 INFO  [TDDL] X-NIO-Client /127.0.0.1:53860 to /127.0.0.1:32886 connect success, connect time: 94us., tddl version: 5.4.19-20240819
2024-08-19 10:07:14.355 ERROR ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53798 to /127.0.0.1:32886 EOF.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-10001][ERR_X_PROTOCOL_CLIENT] X-NIO-Client /127.0.0.1:53798 to /127.0.0.1:32886 EOF.
        at com.alibaba.polardbx.rpc.net.NIOClient.read(NIOClient.java:343)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.read(NIOReactor.java:124)
        at com.alibaba.polardbx.rpc.net.NIOReactor$R.run(NIOReactor.java:90)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by strongduanmu** [comment]
请问这个异常，兄弟解决了吗？

**Comment by lreeze123** [comment]
没有，最后定位到socket通道接收的包不一致导致鉴权失败，但不知道为啥包不一致

**Comment by strongduanmu** [comment]
我看 PolarDB-X 容器里面 galaxyXProtocol=2，本地启动的代码里面 galaxyXProtocol=1，这个看起来是控制协议的，但是我进容器把 galaxyXProtocol=1，也没有效果，还是报错。

**Comment by strongduanmu** [comment]
这个问题解决了，应该是 galaxyXProtocol 和 metaDbXprotoPort 设置的不对，IDEA 启动时本地配置应该和容器保持一致，此外，容器暴露的端口应该是 34886。具体可以参考文章：https://strongduanmu.com/blog/polardb-x-dev-environment-setup-note.html#err_x_protocol_client-%E5%BC%82%E5%B8%B8%E6%8E%92%E6%9F%A5

**Comment by lreeze123** [comment]
可以可以，兄弟厉害，我去试试
