### ISSUE TITLE
[PXC-9001][ERR_GMS_GENERIC] failed to create default db

### ISSUE THREAD

**Issue by cheeloosoft** [polardb/polardbx-sql#38]
2021-12-01 09:48:07.466 [main] ERROR com.alibaba.polardbx.CobarConfig - [] Failed to init cobar server.
com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-9001][ERR_GMS_GENERIC] failed to create default db, err is ERR-CODE: [PXC-9001][ERR_GMS_GENERIC] No found any storage inst of metaDb. .
        at com.alibaba.polardbx.gms.topology.DbTopologyManager.createInternalSystemDbIfNeed(DbTopologyManager.java:223)
        at com.alibaba.polardbx.gms.topology.SystemDbHelper.checkOrCreateDefaultDb(SystemDbHelper.java:61)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initSystemDbIfNeed(MetaDbDataSource.java:420)
        at com.alibaba.polardbx.config.loader.ServerLoader.initPolarDbXComponents(ServerLoader.java:248)
        at com.alibaba.polardbx.config.loader.ServerLoader.load(ServerLoader.java:181)
        at com.alibaba.polardbx.config.loader.ServerLoader.doInit(ServerLoader.java:91)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
        at com.alibaba.polardbx.CobarConfig.initCobarConfig(CobarConfig.java:68)
        at com.alibaba.polardbx.CobarConfig.<init>(CobarConfig.java:61)
        at com.alibaba.polardbx.CobarServer.<init>(CobarServer.java:141)
        at com.alibaba.polardbx.CobarServer.<clinit>(CobarServer.java:95)
        at com.alibaba.polardbx.server.TddlLauncher.main(TddlLauncher.java:82)
Caused by: com.alibaba.polardbx.common.exception.TddlRuntimeException: ERR-CODE: [PXC-9001][ERR_GMS_GENERIC] No found any storage inst of metaDb.
        at com.alibaba.polardbx.gms.topology.DbTopologyManager.createInternalSystemDbIfNeed(DbTopologyManager.java:208)
        ... 11 common frames omitted
[Uploading PXC-9001 数据库.txt…]()

**Comment by cheeloosoft** [comment]
[PXC-9001.tar.gz](https://github.com/ApsaraDB/galaxysql/files/7630467/PXC-9001.tar.gz)
应用logs/tddl下的日志

**Comment by pyson** [comment]
"No found any storage inst of metaDb" means cn can NOT find any DN info from metadb ,maybe the dn infos of metadb is invalid.

**Comment by vettalwu** [comment]
@cheeloosoft  How do you deploy this polardbx cluster?  pxd, k8s or source code?

**Comment by cheeloosoft** [comment]
source code  on CentOS Linux release 7.6.1810 
single node

**Comment by cheeloosoft** [comment]
conf/server.properties
# PolarDB-X 服务端口
serverPort=8527
# PolarDB-X RPC 端口
rpcPort=9090
 # MetaDB地址
metaDbAddr=127.0.0.1:4886
# MetaDB私有协议端口
metaDbXprotoPort=32886
# MetaDB用户
metaDbUser=my_polarx
metaDbName=polardbx_meta_db_polardbx
# PolarDB-X实例名
instanceId=polardbx-polardbx

galaxyXProtocol=1

metaDbPasswd=7pKen4TpFua3pZBZigJAnAAiRflEzLSTo86sJKStSY8=

**Comment by vettalwu** [comment]
@cheeloosoft Do you specify the dn list when initialize PolarDB-X? 

![image](https://user-images.githubusercontent.com/92501707/144183347-30635de7-4afb-4999-865e-d88ea22762b2.png)

**Comment by cheeloosoft** [comment]
Initialization command

bin/startup.sh \
    -I \
    -P asdf1234ghjk5678 \
    -d 127.0.0.1:4886:32886 \
    -r "" \
    -u polardbx_root \
    -S "123456"


Generate password for user: my_polarx && _#_Q9_7@vW4@)0#R9@W5&6#F7$ 数据库的用户密码
Encrypted password: 7pKen4TpFua3pZBZigJAnAAiRflEzLSTo86sJKStSY8=
The property file is resident at resource file, skip saving password into it
 ======== Paste following configurations to conf/server.properties ! ======= 
metaDbPasswd=7pKen4TpFua3pZBZigJAnAAiRflEzLSTo86sJKStSY8=
 ======== Paste above configurations to conf/server.properties ! =======

**Comment by cheeloosoft** [comment]
logs/tddl/meta-db.log
2021-12-01 16:49:00.629 ERROR  [TDDL] Failed to init meta db, err is, tddl version: 5.4.12-SNAPSHOT
com.alibaba.polardbx.common.exception.TddlNestableRuntimeException: null
        at com.alibaba.polardbx.common.utils.GeneralUtil.nestedException(GeneralUtil.java:221)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:56)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.getInstance(MetaDbDataSource.java:463)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:489)
        at com.alibaba.polardbx.config.loader.ServerLoader.initPolarDbXComponents(ServerLoader.java:207)
        at com.alibaba.polardbx.config.loader.ServerLoader.load(ServerLoader.java:181)
        at com.alibaba.polardbx.config.loader.ServerLoader.doInit(ServerLoader.java:91)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
        at com.alibaba.polardbx.CobarConfig.initCobarConfig(CobarConfig.java:68)
        at com.alibaba.polardbx.CobarConfig.<init>(CobarConfig.java:61)
        at com.alibaba.polardbx.CobarServer.<init>(CobarServer.java:141)
        at com.alibaba.polardbx.CobarServer.<clinit>(CobarServer.java:95)
        at com.alibaba.polardbx.server.TddlLauncher.main(TddlLauncher.java:82)
Caused by: java.lang.NullPointerException: null
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:179)
        at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.doInit(MetaDbDataSource.java:121)
        at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43)
        ... 11 common frames omitted

in MetaDbDataSource metaDbAvailableAddr is null

**Comment by Cleverdada** [comment]
> @vettalwu logs/tddl/meta-db.log 2021-12-01 16:49:00.629 ERROR [TDDL] Failed to init meta db, err is, tddl version: 5.4.12-SNAPSHOT com.alibaba.polardbx.common.exception.TddlNestableRuntimeException: null at com.alibaba.polardbx.common.utils.GeneralUtil.nestedException(GeneralUtil.java:221) at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:56) at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.getInstance(MetaDbDataSource.java:463) at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:489) at com.alibaba.polardbx.config.loader.ServerLoader.initPolarDbXComponents(ServerLoader.java:207) at com.alibaba.polardbx.config.loader.ServerLoader.load(ServerLoader.java:181) at com.alibaba.polardbx.config.loader.ServerLoader.doInit(ServerLoader.java:91) at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43) at com.alibaba.polardbx.CobarConfig.initCobarConfig(CobarConfig.java:68) at com.alibaba.polardbx.CobarConfig.(CobarConfig.java:61) at com.alibaba.polardbx.CobarServer.(CobarServer.java:141) at com.alibaba.polardbx.CobarServer.(CobarServer.java:95) at com.alibaba.polardbx.server.TddlLauncher.main(TddlLauncher.java:82) Caused by: java.lang.NullPointerException: null at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.initMetaDbDataSource(MetaDbDataSource.java:179) at com.alibaba.polardbx.gms.metadb.MetaDbDataSource.doInit(MetaDbDataSource.java:121) at com.alibaba.polardbx.common.model.lifecycle.AbstractLifecycle.init(AbstractLifecycle.java:43) ... 11 common frames omitted
> 
> **in MetaDbDataSource metaDbAvailableAddr is null**

pls copy the  "metaDbPasswd=7pKen4TpFua3pZBZigJAnAAiRflEzLSTo86sJKStSY8=" to conf/server.properties  and restart
